[package]
name = "systest"
version = "0.2.0"
authors = ["Saulius Grigaliunas <saulius@ninja.lt>"]
build = "build.rs"

[dependencies]
croaring-sys = { path = "../croaring-sys" }
libc = "0.2"

[build-dependencies]
ctest = { git = "https://github.com/alexcrichton/ctest" }
