[package]
name = "croaring-sys"
version = "0.6.1"
edition = "2021"
authors = ["Saulius Grigaliunas <saulius@ninja.lt>"]
license = "Apache-2.0"
repository = "https://github.com/saulius/croaring-rs.git"
readme = "../README.md"
documentation = "https://docs.rs/croaring-sys"
build = "build.rs"
description = "Raw bindings to CRoaring"

[lib]
doctest = false

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
bindgen = { version = "0.59", default-features = false, features = ["runtime"] }
